version: '3'
services:
  # db:
  #   image: postgres:10.3-alpine
  #   container_name: postgres01
  nginx:
    image: nginx
    container_name: nginx01
    ports:
      - "8000:8000"
    volumes:
      - ./app_django
      - ./config/nginx:/etc/nginx/conf.d
    # depends_on:
    #   - web
  web:
    build: .
    container_name: django01
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata authentication/fixture/groups.json && service supervisor start && service supervisor status && python manage.py runserver 0.0.0.0:8000"
    # command: service supervisor start && service supervisor status
    # depends_on:
    #   - db
    volumes:
      - ./app_django
    expose:
      - "8000"
    restart: always